name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npx changelogithub
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Build artifacts
        run: |
          pipx run build
      - name: Test Build
        run: |
          python -m venv fresh_env
          . fresh_env/bin/activate
          pip install dist/*.whl
          findpython --all
      - name: Upload to Pypi
        run: |
          pipx run twine upload --username __token__ --password ${{ secrets.PYPI_TOKEN }} dist/*
